FROM onesaitplatform/architecture-base-openjdk-8:latest

# Metadata
LABEL module.maintainer="onesaitplatform@indra.es" \
	  module.name="admin"	

ADD *-exec.jar app.jar

EXPOSE 8080

ENV JAVA_OPTS="$JAVA_OPTS -Xms1G -Xmx3G"

ENTRYPOINT sh -c "java $JAVA_OPTS -Dspring.application.json=$ONESAIT_PROPERTIES -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=docker -jar /app.jar" && 1
